import mongoose from 'mongoose';
import connectDB from '../src/config/db.js';
import Product from '../src/models/Product.js';

const unsplash = (id) => `https://images.unsplash.com/${id}?w=800&q=80&auto=format&fit=crop`;

export const catalog = [
  // ==========================================
  // --- MEN'S SECTION (Strictly Men's Apparel) ---
  // ==========================================

  // --- Men's Shirts ---
  {
    name: 'Classic Oxford Button-Down Shirt',
    description: 'Tailored regular-fit oxford shirt in 100% combed cotton with crisp collar and pearlescent buttons.',
    category: 'Shirts',
    gender: 'men',
    price: 1499,
    brand: 'STYLIO Classic',
    colors: ['Sky Blue', 'Crisp White', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 75,
    imageUrl: unsplash('photo-1596755094514-f87e34085b2c'),
    tags: ['shirt', 'oxford', 'formal', 'button-down', 'men'],
    featured: true,
  },
  {
    name: 'Cuban Collar Linen Resort Shirt',
    description: 'Relaxed airy linen-blend shirt with a retro camp collar, tailored for sunny holidays and evenings.',
    category: 'Shirts',
    gender: 'men',
    price: 1799,
    brand: 'STYLIO Summer',
    colors: ['Sage Green', 'Sand Cream', 'Dusty Rose'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 60,
    imageUrl: unsplash('photo-1602810318383-e386cc2a3ccf'),
    tags: ['shirt', 'linen', 'resort', 'cuban collar', 'men'],
    featured: true,
  },
  {
    name: 'Heavyweight Utility Canvas Overshirt',
    description: 'Sturdy 320 GSM cotton twill overshirt with dual chest flap pockets and antique brass buttons.',
    category: 'Shirts',
    gender: 'men',
    price: 2199,
    brand: 'STYLIO Street',
    colors: ['Khaki Tan', 'Army Olive', 'Washed Black'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    stock: 45,
    imageUrl: unsplash('photo-1598033129183-c4f50c736f10'),
    tags: ['overshirt', 'utility', 'jacket', 'canvas', 'shirt', 'men'],
    featured: true,
  },
  {
    name: 'Vintage Check Brushed Flannel Shirt',
    description: 'Warm brushed cotton flannel featuring a heritage buffalo check pattern. Extra soft against skin.',
    category: 'Shirts',
    gender: 'men',
    price: 1899,
    brand: 'STYLIO Urban',
    colors: ['Burgundy Plaid', 'Forest Green Plaid'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 55,
    imageUrl: unsplash('photo-1604014237800-1c9102c219da'),
    tags: ['flannel', 'check', 'plaid', 'warm', 'shirt', 'men'],
  },
  {
    name: 'Monochrome Slim Luxe Dress Shirt',
    description: 'Wrinkle-resistant luxury stretch poplin shirt designed for crisp evening looks and formal suits.',
    category: 'Shirts',
    gender: 'men',
    price: 1999,
    brand: 'STYLIO Luxe',
    colors: ['Jet Black', 'Pure White'],
    sizes: ['38', '40', '42', '44'],
    stock: 65,
    imageUrl: unsplash('photo-1603252109303-2751441dd157'),
    tags: ['dress shirt', 'formal', 'black shirt', 'luxury', 'men'],
  },
  {
    name: 'Breton Striped Casual Cotton Shirt',
    description: 'Modern vertical-stripe long-sleeve casual shirt with soft-wash finish for effortless layering.',
    category: 'Shirts',
    gender: 'men',
    price: 1399,
    brand: 'STYLIO Basics',
    colors: ['Navy Stripe', 'Olive Stripe'],
    sizes: ['M', 'L', 'XL'],
    stock: 50,
    imageUrl: unsplash('photo-1607345366928-199ea26cfe3e'),
    tags: ['shirt', 'striped', 'casual', 'layering', 'men'],
  },

  // --- Men's T-Shirts ---
  {
    name: 'Essential Cotton Crew Tee',
    description: 'Soft breathable 100% organic cotton t-shirt cut for a relaxed everyday fit with ribbed neckline.',
    category: 'T-Shirts',
    gender: 'men',
    price: 799,
    brand: 'STYLIO Basics',
    colors: ['White', 'Black', 'Grey'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 120,
    imageUrl: unsplash('photo-1583743814966-8936f5b7be1a'),
    tags: ['basic', 'cotton', 'everyday', 't-shirt', 'men'],
  },
  {
    name: 'Graphic Street Oversized Tee',
    description: 'Bold graphic print tee with heavyweight 240 GSM pre-shrunk cotton fabric.',
    category: 'T-Shirts',
    gender: 'men',
    price: 1099,
    brand: 'STYLIO Street',
    colors: ['Black', 'Navy'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 80,
    imageUrl: unsplash('photo-1576566588028-4147f3842f27'),
    tags: ['graphic', 'streetwear', 'oversized', 't-shirt', 'men'],
  },
  {
    name: 'Supima Cotton Textured Polo',
    description: 'Breathable honeycomb piqué polo t-shirt with ribbed tipping and mother-of-pearl buttons.',
    category: 'T-Shirts',
    gender: 'men',
    price: 1499,
    brand: 'STYLIO Luxe',
    colors: ['Dark Navy', 'Forest Green', 'Burgundy'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 70,
    imageUrl: unsplash('photo-1618354691373-d851c5c3a990'),
    tags: ['polo', 'supima', 'collar', 'smart casual', 't-shirt', 'men'],
  },
  {
    name: 'Tokyo Underground Graphic Tee',
    description: 'Front and back screen-printed streetwear tee made from pre-shrunk carded cotton.',
    category: 'T-Shirts',
    gender: 'men',
    price: 999,
    brand: 'STYLIO Street',
    colors: ['Chalk White', 'Matte Black'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    stock: 110,
    imageUrl: unsplash('photo-1521572267360-ee0c2909d518'),
    tags: ['graphic tee', 'streetwear', 'tokyo', 't-shirt', 'men'],
  },
  {
    name: 'Acid Wash Heavyweight Oversized Tee',
    description: 'Drop-shoulder relaxed 260 GSM t-shirt with vintage mineral wash texture and raw hems.',
    category: 'T-Shirts',
    gender: 'men',
    price: 1199,
    brand: 'STYLIO Street',
    colors: ['Charcoal Mineral', 'Faded Clay'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 90,
    imageUrl: unsplash('photo-1503342217505-b0a15ec3261c'),
    tags: ['oversized', 'acid wash', 't-shirt', 'streetwear', 'men'],
  },
  {
    name: 'Waffle Knit Long Sleeve Thermal Tee',
    description: 'Thermal waffle-stitch crew neck pullover providing warmth, texture, and a relaxed silhouette.',
    category: 'T-Shirts',
    gender: 'men',
    price: 1299,
    brand: 'STYLIO Studio',
    colors: ['Oatmeal', 'Slate Blue', 'Charcoal'],
    sizes: ['M', 'L', 'XL'],
    stock: 55,
    imageUrl: unsplash('photo-1581655353564-df123a1eb820'),
    tags: ['waffle', 'thermal', 'long sleeve', 'crewneck', 't-shirt', 'men'],
  },

  // --- Men's Hoodies ---
  {
    name: 'Oversized Heavyweight Fleece Hoodie',
    description: 'Ultra-soft 400 GSM brushed fleece hoodie with double-layer hood and dropped shoulder silhouette.',
    category: 'Hoodies',
    gender: 'men',
    price: 1999,
    brand: 'STYLIO Street',
    colors: ['Heather Grey', 'Charcoal', 'Muted Olive'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 60,
    imageUrl: unsplash('photo-1556821840-3a63f95609a7'),
    tags: ['hoodie', 'fleece', 'streetwear', 'oversized', 'men'],
    featured: true,
  },
  {
    name: 'Zip-Up Technical Athletic Hoodie',
    description: 'Water-resistant stretch performance hoodie with bonded zip pockets and ergonomic thumb loops.',
    category: 'Hoodies',
    gender: 'men',
    price: 2299,
    brand: 'STYLIO Active',
    colors: ['Pitch Black', 'Slate Grey'],
    sizes: ['M', 'L', 'XL'],
    stock: 50,
    imageUrl: unsplash('photo-1509942774463-acf339cf87d5'),
    tags: ['hoodie', 'zip-up', 'technical', 'sport', 'men'],
  },
  {
    name: 'Minimalist French Terry Sweatshirt',
    description: 'Pre-shrunk 100% loopback cotton crewneck sweatshirt with ribbed cuffs and understated hem branding.',
    category: 'Hoodies',
    gender: 'men',
    price: 1799,
    brand: 'STYLIO Studio',
    colors: ['Camel Beige', 'Washed Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 65,
    imageUrl: unsplash('photo-1620799140408-edc6dcb6d633'),
    tags: ['sweatshirt', 'crewneck', 'french terry', 'minimal', 'men'],
  },

  // --- Men's Jackets ---
  {
    name: 'Classic Denim Trucker Jacket',
    description: 'Authentic 13.5 oz denim jacket with shank buttons, twin chest pockets, and waist adjusters.',
    category: 'Jackets',
    gender: 'men',
    price: 2899,
    brand: 'STYLIO Denim',
    colors: ['Stonewash Indigo', 'Washed Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 45,
    imageUrl: unsplash('photo-1576871337622-98d48d1cf531'),
    tags: ['denim jacket', 'trucker', 'outerwear', 'men'],
    featured: true,
  },
  {
    name: 'Quilted Matte Winter Puffer Jacket',
    description: 'Thermal insulated cold-weather puffer jacket with storm cuffs, fleece-lined pockets, and detachable hood.',
    category: 'Jackets',
    gender: 'men',
    price: 4499,
    brand: 'STYLIO Winter',
    colors: ['Matte Black', 'Olive Drab', 'Navy'],
    sizes: ['M', 'L', 'XL', 'XXL'],
    stock: 35,
    imageUrl: unsplash('photo-1539533018447-63fcce2678e3'),
    tags: ['puffer jacket', 'winter', 'down jacket', 'outerwear', 'men'],
  },
  {
    name: 'Suede Leather Biker Bomber Jacket',
    description: 'Premium goat suede leather bomber with satin lining, antique bronze YKK zip, and ribbed collar.',
    category: 'Jackets',
    gender: 'men',
    price: 5999,
    brand: 'STYLIO Luxe',
    colors: ['Cognac Tan', 'Dark Espresso'],
    sizes: ['M', 'L', 'XL'],
    stock: 25,
    imageUrl: unsplash('photo-1487222477894-8943e31ef7b2'),
    tags: ['leather jacket', 'suede', 'bomber', 'luxury', 'men'],
  },
  {
    name: 'Tailored Wool-Blend Single Breasted Overcoat',
    description: 'Notched lapel wool-cashmere blend structured overcoat for sophisticated winter tailoring.',
    category: 'Jackets',
    gender: 'men',
    price: 6499,
    brand: 'STYLIO Formal',
    colors: ['Camel', 'Charcoal Melange'],
    sizes: ['38', '40', '42', '44'],
    stock: 30,
    imageUrl: unsplash('photo-1544022613-e87ca75a784a'),
    tags: ['overcoat', 'wool coat', 'formal', 'winter', 'men'],
  },

  // --- Men's Jeans & Pants ---
  {
    name: 'Slim Tapered Raw Denim Jeans',
    description: 'Deep indigo Japanese selvedge denim with classic 5-pocket construction and copper rivets.',
    category: 'Jeans',
    gender: 'men',
    price: 2199,
    brand: 'STYLIO Denim',
    colors: ['Raw Indigo', 'Washed Black'],
    sizes: ['30', '32', '34', '36'],
    stock: 80,
    imageUrl: unsplash('photo-1541099649105-f69ad21f3246'),
    tags: ['jeans', 'raw denim', 'selvedge', 'slim', 'men'],
    featured: true,
  },
  {
    name: 'Straight Leg Selvedge Vintage Jeans',
    description: 'Classic mid-rise straight cut jeans crafted with a gentle vintage stone wash and contrast stitching.',
    category: 'Jeans',
    gender: 'men',
    price: 2499,
    brand: 'STYLIO Denim',
    colors: ['Vintage Blue', 'Light Wash'],
    sizes: ['30', '32', '34', '36'],
    stock: 65,
    imageUrl: unsplash('photo-1604176354204-9268737828e4'),
    tags: ['jeans', 'straight leg', 'vintage', 'denim', 'men'],
  },
  {
    name: 'Pleated Relaxed Fit Chino Trousers',
    description: 'Double pleated high-density cotton twill trousers tailored with a clean tapered leg and coin pocket.',
    category: 'Pants',
    gender: 'men',
    price: 2199,
    brand: 'STYLIO Classic',
    colors: ['Khaki Beige', 'Dark Navy', 'Olive Green'],
    sizes: ['30', '32', '34', '36'],
    stock: 60,
    imageUrl: unsplash('photo-1624378439575-d8705ad7ae80'),
    tags: ['chino', 'trousers', 'pleated', 'smart casual', 'men'],
  },
  {
    name: 'Tactical Multi-Pocket Cargo Pants',
    description: 'Military-grade ripstop cotton cargo pants with six reinforced utility pockets and ankle drawstrings.',
    category: 'Pants',
    gender: 'men',
    price: 2499,
    brand: 'STYLIO Street',
    colors: ['Army Green', 'Pitch Black'],
    sizes: ['30', '32', '34', '36'],
    stock: 50,
    imageUrl: unsplash('photo-1517445312882-bc9910d016b7'),
    tags: ['cargo', 'tactical', 'streetwear', 'pants', 'men'],
  },
  {
    name: 'Tailored Slim Wool-Blend Trousers',
    description: 'Sharp formal trousers with French fly closure, curtained waistband, and pressed creased leg.',
    category: 'Pants',
    gender: 'men',
    price: 2699,
    brand: 'STYLIO Formal',
    colors: ['Charcoal Grey', 'Midnight Navy'],
    sizes: ['30', '32', '34', '36', '38'],
    stock: 45,
    imageUrl: unsplash('photo-1490114538077-0a7f8cb49891'),
    tags: ['formal trousers', 'suit pants', 'wool', 'men'],
  },
  {
    name: 'Linen Drawstring Summer Trousers',
    description: 'Lightweight pure linen trousers with elasticated drawstring waist for effortless summer sophistication.',
    category: 'Pants',
    gender: 'men',
    price: 1899,
    brand: 'STYLIO Summer',
    colors: ['Natural Sand', 'White', 'Sage'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 55,
    imageUrl: unsplash('photo-1473966968600-fa801b869a1a'),
    tags: ['linen', 'drawstring', 'summer', 'breathable', 'men'],
  },
  {
    name: 'Heavy French Terry Lounge Joggers',
    description: 'Super-soft 360 GSM combed cotton joggers with deep welt pockets and thick ribbed cuffs.',
    category: 'Pants',
    gender: 'men',
    price: 1599,
    brand: 'STYLIO Active',
    colors: ['Muted Grey', 'Black'],
    sizes: ['S', 'M', 'L', 'XL'],
    stock: 70,
    imageUrl: unsplash('photo-1506629082955-511b1aa562c8'),
    tags: ['joggers', 'sweatpants', 'lounge', 'french terry', 'men'],
  },

  // ==========================================
  // --- WOMEN'S SECTION (Strictly Women's Apparel) ---
  // ==========================================

  // --- Women's Dresses ---
  {
    name: 'Floral Wrap Midi Dress',
    description: 'Flattering silhouette wrap dress in lightweight georgette with a romantic floral print.',
    category: 'Dresses',
    gender: 'women',
    price: 2499,
    brand: 'STYLIO Bloom',
    colors: ['Floral Blue', 'Floral Pink'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 45,
    imageUrl: unsplash('photo-1515372039744-b8f02a3ae446'),
    tags: ['floral', 'midi', 'wrap', 'party', 'dress', 'women'],
    featured: true,
  },
  {
    name: 'Slip Silk Evening Satin Dress',
    description: 'Elegant bias-cut slip dress in 100% mulberry satin designed to cascade effortlessly down the body.',
    category: 'Dresses',
    gender: 'women',
    price: 5499,
    brand: 'STYLIO Luxe',
    colors: ['Champagne', 'Black'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 30,
    imageUrl: unsplash('photo-1509631179647-0177331693ae'),
    tags: ['silk', 'evening', 'slip', 'formal', 'dress', 'women'],
    featured: true,
  },
  {
    name: 'Floral Cottagecore Milkmaid Midi Dress',
    description: 'Vintage-inspired sweetheart neckline dress with gathered bust, smocked back, and puff sleeves.',
    category: 'Dresses',
    gender: 'women',
    price: 2799,
    brand: 'STYLIO Bloom',
    colors: ['Pastel Buttercup', 'Lavender Mist'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 40,
    imageUrl: unsplash('photo-1572804013309-59a88b7e92f1'),
    tags: ['cottagecore', 'milkmaid', 'midi dress', 'floral', 'women'],
  },
  {
    name: 'Emerald Satin Bias Cut Evening Dress',
    description: 'Couture cowl-neck bias dress in lustrous heavy emerald satin with an open back and delicate straps.',
    category: 'Dresses',
    gender: 'women',
    price: 3499,
    brand: 'STYLIO Luxe',
    colors: ['Emerald Green', 'Wine Red'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 35,
    imageUrl: unsplash('photo-1595777457583-95e059d581b8'),
    tags: ['evening gown', 'emerald', 'cowl neck', 'satin dress', 'women'],
  },
  {
    name: 'Off-Shoulder Ruched Velvet Party Mini Dress',
    description: 'Plush stretch velvet mini dress featuring an off-shoulder foldover neckline and body-hugging ruching.',
    category: 'Dresses',
    gender: 'women',
    price: 2899,
    brand: 'STYLIO Night',
    colors: ['Midnight Ruby', 'Obsidian Black'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 30,
    imageUrl: unsplash('photo-1566174053879-31528523f8ae'),
    tags: ['velvet', 'mini dress', 'party', 'off-shoulder', 'women'],
  },
  {
    name: 'Tiered Bohemian Smocked Maxi Sundress',
    description: 'Effortless tiered cotton-voile maxi dress with elasticated smocked bodice and adjustable ribbon ties.',
    category: 'Dresses',
    gender: 'women',
    price: 2999,
    brand: 'STYLIO Bloom',
    colors: ['Sun Gold', 'Earthy Terracotta'],
    sizes: ['S', 'M', 'L'],
    stock: 50,
    imageUrl: unsplash('photo-1502716119720-b23a93e5fe1b'),
    tags: ['boho', 'maxi dress', 'tiered', 'sundress', 'women'],
  },
  {
    name: 'Sunburst Botanical Printed Summer Dress',
    description: 'Airy A-line summer dress featuring hand-painted botanical motifs with a breathable cotton-linen blend.',
    category: 'Dresses',
    gender: 'women',
    price: 2599,
    brand: 'STYLIO Bloom',
    colors: ['Botanical Cream', 'Citrus Orange'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 45,
    imageUrl: unsplash('photo-1496747611176-843222e1e57c'),
    tags: ['summer dress', 'botanical', 'print', 'women'],
  },

  // --- Women's Tops & Blouses ---
  {
    name: 'Embroidered Peasant Boho Blouse',
    description: 'Breezy woven cotton peasant blouse with intricate floral chain-stitch embroidery and tassel ties.',
    category: 'Shirts',
    gender: 'women',
    price: 1599,
    brand: 'STYLIO Boho',
    colors: ['Ivory Floral', 'Oatmeal Blue'],
    sizes: ['S', 'M', 'L'],
    stock: 60,
    imageUrl: unsplash('photo-1564584217132-2271feaeb3c5'),
    tags: ['blouse', 'boho', 'embroidery', 'peasant', 'women'],
  },
  {
    name: 'Oversized Champagne Silk Blouse',
    description: 'Drapey silk crepe de chine shirt with covered placket, French cuffs, and relaxed shoulders.',
    category: 'Shirts',
    gender: 'women',
    price: 1899,
    brand: 'STYLIO Chic',
    colors: ['Champagne Pearl', 'Ivory'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 55,
    imageUrl: unsplash('photo-1551803091-e20673f15770'),
    tags: ['silk blouse', 'shirt', 'formal', 'luxury', 'women'],
  },
  {
    name: 'Ribbed Sweetheart Knit Crop Top',
    description: 'Form-fitting ribbed knit crop top with a feminine sweetheart neckline and sculptured bust seam.',
    category: 'T-Shirts',
    gender: 'women',
    price: 1099,
    brand: 'STYLIO Chic',
    colors: ['Creamy Ecru', 'Cocoa Brown', 'Black'],
    sizes: ['XS', 'S', 'M'],
    stock: 75,
    imageUrl: unsplash('photo-1503342394128-c104d54dba01'),
    tags: ['crop top', 'sweetheart', 'knit', 'women'],
  },
  {
    name: 'Linen Two-Piece Co-Ord Set',
    description: 'Matching crop tie-front top and relaxed high-waisted shorts cut in breezy 100% pure linen.',
    category: 'Dresses',
    gender: 'women',
    price: 2899,
    brand: 'STYLIO Summer',
    colors: ['Sage Green', 'Natural Sand'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 40,
    imageUrl: unsplash('photo-1515886657613-9f3515b0c78f'),
    tags: ['co-ord', 'two-piece', 'linen', 'summer set', 'women'],
    featured: true,
  },

  // --- Women's Jeans, Skirts & Pants ---
  {
    name: 'Mom Fit High-Rise Ripped Jeans',
    description: 'Authentic 90s vintage wash high-waisted mom jeans with subtle knee distressing and ankle taper.',
    category: 'Jeans',
    gender: 'women',
    price: 2399,
    brand: 'STYLIO Denim',
    colors: ['Bleached Stone', 'Classic Indigo'],
    sizes: ['26', '28', '30', '32'],
    stock: 65,
    imageUrl: unsplash('photo-1576995853123-5a10305d93c0'),
    tags: ['mom jeans', 'ripped', 'high rise', 'denim', 'women'],
  },
  {
    name: 'Retro 70s High-Rise Flared Jeans',
    description: 'Hourglass-contouring flared bootcut jeans in premium stretch denim with a sculpted waistline.',
    category: 'Jeans',
    gender: 'women',
    price: 2399,
    brand: 'STYLIO Denim',
    colors: ['Dark Wash Indigo', 'Black'],
    sizes: ['26', '28', '30', '32'],
    stock: 55,
    imageUrl: unsplash('photo-1582533561751-ef6f6ab93a2e'),
    tags: ['flared jeans', '70s', 'bootcut', 'denim', 'women'],
  },
  {
    name: 'High-Waist Wide-Leg Linen Palazzo Pants',
    description: 'Flowing floor-sweeping palazzo trousers with flattering tailored front pleats and side zip.',
    category: 'Pants',
    gender: 'women',
    price: 1999,
    brand: 'STYLIO Bloom',
    colors: ['Oatmeal Cream', 'Clay Peach'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 60,
    imageUrl: unsplash('photo-1509551388413-e18d0ac5d495'),
    tags: ['palazzo', 'wide leg', 'linen pants', 'high waist', 'women'],
  },
  {
    name: 'Pleated High-Waist A-Line Tennis Skirt',
    description: 'Sporty-chic structured box pleat mini skirt with built-in undershorts and hidden side zipper.',
    category: 'Pants',
    gender: 'women',
    price: 1399,
    brand: 'STYLIO Active',
    colors: ['Crisp White', 'Pinstripe Navy'],
    sizes: ['XS', 'S', 'M'],
    stock: 70,
    imageUrl: unsplash('photo-1583496661160-fb5886a0aaaa'),
    tags: ['tennis skirt', 'pleated skirt', 'mini skirt', 'women'],
  },

  // --- Women's Jackets & Blazers ---
  {
    name: 'Tailored Double-Breasted Power Blazer',
    description: 'Sculpted hourglass double-breasted blazer with padded shoulders and tortoiseshell buttons.',
    category: 'Jackets',
    gender: 'women',
    price: 3999,
    brand: 'STYLIO Luxe',
    colors: ['Pinstripe Black', 'Desert Camel'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 40,
    imageUrl: unsplash('photo-1591047139829-d91aecb6caea'),
    tags: ['blazer', 'power suit', 'formal', 'double breasted', 'women'],
    featured: true,
  },
  {
    name: 'Cropped Raw-Hem Denim Trucker Jacket',
    description: 'Vintage light wash cropped trucker jacket featuring a frayed hem and custom silver hardware.',
    category: 'Jackets',
    gender: 'women',
    price: 2599,
    brand: 'STYLIO Denim',
    colors: ['Light Vintage Blue'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 50,
    imageUrl: unsplash('photo-1544441893-675973e31985'),
    tags: ['denim jacket', 'cropped', 'raw hem', 'outerwear', 'women'],
  },
  {
    name: 'Belted Double-Breasted Trench Coat',
    description: 'Classic British-tailored water-repellent gabardine trench coat with storm flap and waist belt.',
    category: 'Jackets',
    gender: 'women',
    price: 4999,
    brand: 'STYLIO Chic',
    colors: ['Classic Honey', 'Navy'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 35,
    imageUrl: unsplash('photo-1548624313-0396c75e4b1a'),
    tags: ['trench coat', 'outerwear', 'jacket', 'women'],
    featured: true,
  },
  {
    name: 'Cropped Leather Moto Biker Jacket',
    description: 'Supple lambskin leather moto jacket with asymmetrical front zipper, notch lapels, and epaulettes.',
    category: 'Jackets',
    gender: 'women',
    price: 5499,
    brand: 'STYLIO Street',
    colors: ['Pitch Black'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 30,
    imageUrl: unsplash('photo-1551028719-00167b16eac5'),
    tags: ['leather jacket', 'biker', 'moto', 'outerwear', 'women'],
  },
  {
    name: 'French Puff-Sleeve Linen Square-Neck Blouse',
    description: 'Romantic vintage-cut blouse crafted in airy washed linen with ruched elasticated bodice.',
    category: 'Shirts',
    gender: 'women',
    price: 1699,
    brand: 'STYLIO Bloom',
    colors: ['Crisp White', 'Soft Sage'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 55,
    imageUrl: unsplash('photo-1518049362265-d5b2a6467637'),
    tags: ['blouse', 'puff sleeve', 'linen', 'square neck', 'women'],
  },
  {
    name: 'Chunky Cable-Knit Oversized Cardigan',
    description: 'Cozy fisherman cable-knit cardigan in soft wool blend with oversized tortoiseshell horn buttons.',
    category: 'Jackets',
    gender: 'women',
    price: 2499,
    brand: 'STYLIO Knitwear',
    colors: ['Oatmeal Heather', 'Dusty Rose'],
    sizes: ['XS/S', 'M/L'],
    stock: 45,
    imageUrl: unsplash('photo-1434389677669-e08b4cac3105'),
    tags: ['cardigan', 'knitwear', 'cable knit', 'sweater', 'women'],
  },
  {
    name: 'Ribbed Knit Bodycon Midi Dress',
    description: 'Sculpting ribbed modal jersey midi dress with side slit and mock neck for sleek minimalist silhouette.',
    category: 'Dresses',
    gender: 'women',
    price: 2199,
    brand: 'STYLIO Chic',
    colors: ['Warm Taupe', 'Jet Black'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 40,
    imageUrl: unsplash('photo-1539109136881-3be0616acf4b'),
    tags: ['bodycon', 'midi dress', 'ribbed', 'knit dress', 'women'],
  },
  {
    name: 'Floral Chiffon Ruffle Wrap Blouse',
    description: 'Sheer printed chiffon tie-waist wrap top with flounce sleeves and delicate micro-ruffle trims.',
    category: 'Shirts',
    gender: 'women',
    price: 1499,
    brand: 'STYLIO Bloom',
    colors: ['Floral Noir', 'Blush Bloom'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 60,
    imageUrl: unsplash('photo-1485968579580-b6d095142e6e'),
    tags: ['chiffon', 'wrap top', 'ruffle', 'blouse', 'women'],
  },
  {
    name: 'Pleated Satin A-Line Evening Skirt',
    description: 'High-waisted knife-pleated skirt cut in fluid metallic-sheen satin with comfortable waistband.',
    category: 'Pants',
    gender: 'women',
    price: 2299,
    brand: 'STYLIO Luxe',
    colors: ['Champagne Gold', 'Emerald'],
    sizes: ['XS', 'S', 'M', 'L'],
    stock: 50,
    imageUrl: unsplash('photo-1525507119028-ed4c629a60a3'),
    tags: ['pleated skirt', 'satin', 'midi skirt', 'evening', 'women'],
  },

  // ==========================================
  // --- SHOES & FOOTWEAR SECTION (Strictly Footwear) ---
  // ==========================================
  {
    name: 'Classic White Leather Minimalist Sneakers',
    description: 'Ultra-clean low-top sneakers in Italian full-grain nappa leather with memory foam insoles.',
    category: 'Shoes',
    gender: 'unisex',
    price: 2999,
    brand: 'STYLIO Kicks',
    colors: ['White/White', 'White/Gold'],
    sizes: ['6', '7', '8', '9', '10', '11'],
    stock: 90,
    imageUrl: unsplash('photo-1549298916-b41d501d3772'),
    tags: ['sneakers', 'white sneakers', 'leather', 'shoes', 'footwear'],
    featured: true,
  },
  {
    name: 'Retro Suede Runner Athletic Trainers',
    description: '70s archival running profile with plush hairy suede overlays, nylon mesh, and EVA wedge sole.',
    category: 'Shoes',
    gender: 'unisex',
    price: 3899,
    brand: 'STYLIO Kicks',
    colors: ['Forest Green', 'Retro Cobalt', 'Sand Suede'],
    sizes: ['7', '8', '9', '10', '11'],
    stock: 65,
    imageUrl: unsplash('photo-1600185365483-26d7a4cc7519'),
    tags: ['retro runner', 'trainers', 'suede sneakers', 'shoes'],
    featured: true,
  },
  {
    name: 'Chunky Street Platform Skate Sneakers',
    description: 'Exaggerated chunky platform silhouette with padded skate tongue and high-abrasion rubber outsole.',
    category: 'Shoes',
    gender: 'unisex',
    price: 4499,
    brand: 'STYLIO Street',
    colors: ['Panda Black/White', 'Triple Chalk'],
    sizes: ['6', '7', '8', '9', '10'],
    stock: 50,
    imageUrl: unsplash('photo-1585487000160-6ebcfceb0d03'),
    tags: ['chunky sneakers', 'platform', 'skate', 'streetwear', 'shoes'],
  },
  {
    name: 'Air Cushion Performance Running Shoes',
    description: 'Engineered fly-knit upper runners with full-length nitrogen-infused cushion bounce pods.',
    category: 'Shoes',
    gender: 'unisex',
    price: 4999,
    brand: 'STYLIO Active',
    colors: ['Volt Neon', 'Stealth Charcoal'],
    sizes: ['7', '8', '9', '10', '11'],
    stock: 45,
    imageUrl: unsplash('photo-1595950653106-6c9ebd614d3a'),
    tags: ['running shoes', 'air cushion', 'sports', 'marathon', 'shoes'],
  },
  {
    name: 'Handcrafted Suede Chelsea Ankle Boots',
    description: 'Artisan water-resistant suede chelsea boots with elastic side gussets and Goodyear welted sole.',
    category: 'Shoes',
    gender: 'men',
    price: 5499,
    brand: 'STYLIO Luxe',
    colors: ['Caramel Tan', 'Chocolate Suede'],
    sizes: ['7', '8', '9', '10', '11'],
    stock: 40,
    imageUrl: unsplash('photo-1584735935682-2f2b69dff9d2'),
    tags: ['chelsea boots', 'boots', 'suede', 'formal', 'shoes'],
    featured: true,
  },
  {
    name: 'Classic Italian Leather Oxford Dress Shoes',
    description: 'Burnished calfskin closed-lacing oxford shoes designed for black-tie affairs and formal events.',
    category: 'Shoes',
    gender: 'men',
    price: 5999,
    brand: 'STYLIO Formal',
    colors: ['Black Patent', 'Burnished Cognac'],
    sizes: ['7', '8', '9', '10', '11'],
    stock: 35,
    imageUrl: unsplash('photo-1614252235316-8c857d38b5f4'),
    tags: ['oxford shoes', 'dress shoes', 'leather', 'formal', 'shoes'],
  },
  {
    name: 'Italian Handcrafted Leather Penny Loafers',
    description: 'Buttery calfskin slip-on penny loafers with apron toe stitching and polished stacked leather heel.',
    category: 'Shoes',
    gender: 'men',
    price: 4799,
    brand: 'STYLIO Luxe',
    colors: ['Bordeaux Cherry', 'Deep Espresso'],
    sizes: ['7', '8', '9', '10', '11'],
    stock: 45,
    imageUrl: unsplash('photo-1533867617858-e7b97e060509'),
    tags: ['penny loafers', 'loafers', 'slip on', 'shoes'],
  },
  {
    name: 'High-Top Retro Canvas Basketball Sneakers',
    description: 'Heritage ankle-cut high top vulcanized canvas kicks with vintage toe cap and rubber badge.',
    category: 'Shoes',
    gender: 'unisex',
    price: 2799,
    brand: 'STYLIO Kicks',
    colors: ['Midnight Black', 'Vintage White'],
    sizes: ['6', '7', '8', '9', '10', '11'],
    stock: 80,
    imageUrl: unsplash('photo-1607522370275-f14206abe5d3'),
    tags: ['high-top', 'canvas', 'sneakers', 'retro basketball', 'shoes'],
  },
  {
    name: 'Pro Aerodynamic Speed Running Shoes',
    description: 'Featherlight carbon plate road racers with responsive foam midsole and breathable mesh upper.',
    category: 'Shoes',
    gender: 'unisex',
    price: 4199,
    brand: 'STYLIO Active',
    colors: ['Electric Orange', 'Solar White'],
    sizes: ['7', '8', '9', '10'],
    stock: 40,
    imageUrl: unsplash('photo-1542291026-7eec264c27ff'),
    tags: ['running', 'speed shoes', 'athletic', 'shoes'],
  },
  {
    name: 'Vintage Canvas Low-Top Skate Sneakers',
    description: 'Durable heavyweight cotton canvas skate shoes with waffle rubber grip tread and padded collar.',
    category: 'Shoes',
    gender: 'unisex',
    price: 2499,
    brand: 'STYLIO Street',
    colors: ['Mustard Gold', 'True White'],
    sizes: ['6', '7', '8', '9', '10'],
    stock: 65,
    imageUrl: unsplash('photo-1525966222134-fcfa99b8ae77'),
    tags: ['skate shoes', 'canvas sneakers', 'casual shoes', 'shoes'],
  },
  {
    name: "Women's Strappy Stiletto Heeled Sandals",
    description: 'Minimalist tubular strap sandals on a sculpted 85mm stiletto heel with square open toe.',
    category: 'Shoes',
    gender: 'women',
    price: 3699,
    brand: 'STYLIO Luxe',
    colors: ['Metallic Gold', 'Pure Black'],
    sizes: ['5', '6', '7', '8', '9'],
    stock: 35,
    imageUrl: unsplash('photo-1543163521-1bf539c55dd2'),
    tags: ['heels', 'stiletto', 'sandals', 'party shoes', 'shoes', 'women'],
  },

  // ==========================================
  // --- BEAUTY & COSMETICS SECTION (Strictly Beauty) ---
  // ==========================================
  {
    name: 'Atelier Noir Eau De Parfum (100ml)',
    description: 'Exquisite haute fragrance notes of smoked oud wood, damascus rose, amber resin, and vetiver.',
    category: 'Beauty',
    gender: 'unisex',
    price: 3499,
    brand: 'STYLIO Atelier',
    colors: ['100ml Glass Flacon'],
    sizes: ['100ml'],
    stock: 60,
    imageUrl: unsplash('photo-1592945403244-b3fbafd7f539'),
    tags: ['perfume', 'eau de parfum', 'fragrance', 'oud', 'beauty'],
    featured: true,
  },
  {
    name: 'Dewy Glass-Skin Peptide Serum',
    description: 'Triple-molecular hyaluronic acid and copper peptide formula designed to flood skin with deep radiance.',
    category: 'Beauty',
    gender: 'unisex',
    price: 1699,
    brand: 'STYLIO Skin',
    colors: ['30ml Dropper'],
    sizes: ['30ml'],
    stock: 85,
    imageUrl: unsplash('photo-1620916566398-39f1143ab7be'),
    tags: ['serum', 'skincare', 'hyaluronic', 'anti-aging', 'beauty'],
    featured: true,
  },
  {
    name: 'Gilded Horizon 12-Pan Eyeshadow Palette',
    description: 'Ultra-pigmented buttery mattes, metallics, and duo-chrome foil shades for dramatic luxury eye looks.',
    category: 'Beauty',
    gender: 'unisex',
    price: 2499,
    brand: 'STYLIO Beauty',
    colors: ['Sunset Gold / Bronze'],
    sizes: ['12 Shades'],
    stock: 50,
    imageUrl: unsplash('photo-1512496015851-a90fb38ba796'),
    tags: ['eyeshadow', 'palette', 'makeup', 'cosmetics', 'beauty'],
    featured: true,
  },
  {
    name: 'Botanical Glow Radiance Facial Elixir',
    description: 'Cold-pressed cold-infused organic rosehip, jojoba, and squalane oil for overnight skin rejuvenation.',
    category: 'Beauty',
    gender: 'unisex',
    price: 1899,
    brand: 'STYLIO Skin',
    colors: ['50ml Bottle'],
    sizes: ['50ml'],
    stock: 55,
    imageUrl: unsplash('photo-1616683693504-3ea7e9ad6fec'),
    tags: ['face oil', 'elixir', 'skincare', 'radiance', 'beauty'],
  },
  {
    name: 'Soft Flush Baked Mineral Blush',
    description: 'Weightless micro-milled baked blush giving a luminous multidimensional glow that never cakes.',
    category: 'Beauty',
    gender: 'unisex',
    price: 1199,
    brand: 'STYLIO Beauty',
    colors: ['Peachy Nectar', 'Rose Velvet'],
    sizes: ['Compact 8g'],
    stock: 70,
    imageUrl: unsplash('photo-1515688594390-b649af70d282'),
    tags: ['blush', 'mineral', 'glow', 'makeup', 'beauty'],
  },
  {
    name: 'Hydra-Glaze Nourishing Peptide Lip Oil',
    description: 'Non-sticky high-shine lip glaze enriched with sweet almond oil, vitamin E, and plumping peptides.',
    category: 'Beauty',
    gender: 'unisex',
    price: 899,
    brand: 'STYLIO Beauty',
    colors: ['Berry Glaze', 'Clear Honey'],
    sizes: ['6ml'],
    stock: 95,
    imageUrl: unsplash('photo-1583001931096-959e9a1a6223'),
    tags: ['lip oil', 'lip glaze', 'peptides', 'cosmetics', 'beauty'],
  },
  {
    name: 'Translucent Silk Setting & Blur Powder',
    description: 'Micro-fine spherical silica setting powder that blurs fine lines and locks in foundation all day.',
    category: 'Beauty',
    gender: 'unisex',
    price: 1499,
    brand: 'STYLIO Beauty',
    colors: ['Translucent Universal'],
    sizes: ['15g Jar'],
    stock: 65,
    imageUrl: unsplash('photo-1527799820374-dcf8d9d4a388'),
    tags: ['powder', 'setting powder', 'translucent', 'matte', 'beauty'],
  },
  {
    name: 'Ultra-Matte Transfer-Proof Liquid Lipstick',
    description: '16-hour long-wear smudge-proof liquid lipstick with intense pigment payoff and hydrating jojoba wax.',
    category: 'Beauty',
    gender: 'unisex',
    price: 699,
    brand: 'STYLIO Beauty',
    colors: ['Ruby Seduction', 'Nude Allure', 'Crimson Velvet'],
    sizes: ['5ml'],
    stock: 110,
    imageUrl: unsplash('photo-1625093742435-6fa192b6fb10'),
    tags: ['lipstick', 'liquid lipstick', 'matte', 'makeup', 'beauty'],
  },
  {
    name: 'Lash Drama Volumizing Waterproof Mascara',
    description: 'Hourglass bristle wand mascara that curls, lifts, and thickens lashes 5x without clumping or flaking.',
    category: 'Beauty',
    gender: 'unisex',
    price: 649,
    brand: 'STYLIO Beauty',
    colors: ['Carbon Black'],
    sizes: ['10ml'],
    stock: 120,
    imageUrl: unsplash('photo-1631214524020-7e18db9a8f92'),
    tags: ['mascara', 'waterproof', 'lashes', 'eye makeup', 'beauty'],
  },
  {
    name: '10% Vitamin C Radiance Glow Face Serum',
    description: 'Stabilized ethyl ascorbic acid serum that fades dark spots and shields skin against oxidative stressors.',
    category: 'Beauty',
    gender: 'unisex',
    price: 899,
    brand: 'STYLIO Skin',
    colors: ['30ml Bottle'],
    sizes: ['30ml'],
    stock: 80,
    imageUrl: unsplash('photo-1587854692152-cbe660dbde88'),
    tags: ['vitamin c', 'brightening', 'skincare', 'face serum', 'beauty'],
  },
  {
    name: 'Invisible Water-Gel Sunscreen SPF 50+ PA++++',
    description: 'Ultra-lightweight zero white-cast broad spectrum gel sunscreen packed with soothing cica extract.',
    category: 'Beauty',
    gender: 'unisex',
    price: 649,
    brand: 'STYLIO Skin',
    colors: ['50g Tube'],
    sizes: ['50g'],
    stock: 130,
    imageUrl: unsplash('photo-1629198688000-71f23e745b6e'),
    tags: ['sunscreen', 'spf 50', 'cica', 'sun protection', 'beauty'],
  },
  {
    name: 'Gel Finish Salon Shine Nail Enamel Trio',
    description: 'Chip-resistant gel-effect nail lacquer with plumping top coat shine. 7-free and cruelty-free.',
    category: 'Beauty',
    gender: 'unisex',
    price: 499,
    brand: 'STYLIO Nails',
    colors: ['Classic Red', 'French Nude', 'Merlot'],
    sizes: ['3 x 8ml'],
    stock: 90,
    imageUrl: unsplash('photo-1604654894610-df63bc536371'),
    tags: ['nail polish', 'gel finish', 'manicure', 'beauty'],
  },
  {
    name: 'Professional 10-Piece Luxury Makeup Brush Set',
    description: 'Super-dense vegan synthetic brushes with champagne gold ferrules and weighted wooden handles.',
    category: 'Beauty',
    gender: 'unisex',
    price: 999,
    brand: 'STYLIO Tools',
    colors: ['Champagne Gold'],
    sizes: ['10 Brushes + Pouch'],
    stock: 60,
    imageUrl: unsplash('photo-1596462502278-27bfdc403348'),
    tags: ['makeup brushes', 'beauty tools', 'brush set', 'beauty'],
  },
  {
    name: 'Pure Steam-Distilled Rose Water Facial Mist',
    description: '100% pure organic Kannauj damask rose water to balance skin pH, hydrate, and refresh midday glow.',
    category: 'Beauty',
    gender: 'unisex',
    price: 349,
    brand: 'STYLIO Skin',
    colors: ['100ml Spray'],
    sizes: ['100ml'],
    stock: 140,
    imageUrl: unsplash('photo-1571781926291-c477ebfd024b'),
    tags: ['rose water', 'facial mist', 'toner', 'skincare', 'beauty'],
  },
];

async function seed() {
  await connectDB();
  console.log(`Connecting to MongoDB and clearing old products...`);
  await Product.deleteMany({});
  console.log(`Inserting ${catalog.length} perfectly matched, curated products...`);
  
  const inserted = await Product.insertMany(catalog);
  console.log(`Successfully seeded ${inserted.length} products!`);

  const menCount = await Product.countDocuments({ gender: 'men' });
  const womenCount = await Product.countDocuments({ gender: 'women' });
  const shoesCount = await Product.countDocuments({ category: { $in: ['Shoes', 'Sneakers'] } });
  const beautyCount = await Product.countDocuments({ category: 'Beauty' });

  console.log('\n--- VERIFIED PRODUCT COUNTS ---');
  console.log(`Men's Apparel: ${menCount} items`);
  console.log(`Women's Apparel: ${womenCount} items`);
  console.log(`Footwear (Shoes/Sneakers): ${shoesCount} items`);
  console.log(`Beauty & Makeup: ${beautyCount} items`);
  console.log(`Total Catalog Size: ${inserted.length} items`);

  process.exit(0);
}

seed().catch((err) => {
  console.error('Seeding error:', err);
  process.exit(1);
});
